### PR TITLE
RightStyles and Right Comps added

### PR DESCRIPTION
**Pull request by Monsoegianto**
Styles and components added.
Need help with the interactions of the switch!

### CODE REVIEW

**Comment by Peeterlee** [comment]
You need to make if statements
like each switch has to have a const.
and then when it is switched change the value of the its own const.
let's say you switching the normal one and the const name is normalstauts
so when the normalstatus == true and in that statement check if others value is true, and if it is true set it to false

**Comment by Peeterlee** [comment]
he if statments will look like this
if(normal == true){
 if(wide == true){
   setWide(false)
}
if(wider == true){
setWider(false)
}


etcetc

**Comment by Peeterlee** [comment]
so the if statements are checking if the others are on
because the others should be off

**Comment by Peeterlee** [comment]
i added a function so now from the first one each switch has a number from 1 to 4
and each value should be switchnum === its own number

**Comment by Peeterlee** [comment]
each switch should have onvaluechange setswitchnum(its own number)

**Comment by Monsoegianto** [comment]
interactions worked!

working on the flex interaction now,

how do i add 2 styles in view?

**Comment by Peeterlee** [comment]
<View  style={[styles.blah,{botton:0}]}>

**Comment by Peeterlee** [comment]
<View style={[styles.blah, {flex:blah}]}>
you need to make a variable instead of blah and change the value of the variable depends on the switch

**Comment by Monsoegianto** [comment]
but if i only have 1 style, and i have 4 switches to work with, that means i style it one time only?

**Comment by Monsoegianto** [comment]
im not making another view for each switch am i?

**Comment by Peeterlee** [comment]
no you are just changing the flex of the view in the return

**Comment by Monsoegianto** [comment]
<View style={styles.container}>
        <View style={styles.switchContainer}>
      
    <Text>Normal</Text> 
    <Switch
      onValueChange={(itemValue, itemIndex) => {Setswitchnum(1)}}
      value={switchnum === 1}>
    </Switch>
  
    
    <Text>Wide</Text>
    <Switch
       onValueChange={(itemValue, itemIndex) => {Setswitchnum(2)}}
       value={switchnum === 2}>
    </Switch>

so for example that, im only editing the styles in the 2nd view right, but if i want to make the first switch's flex to 3 and second flex to 5, how can i change it individually?

**Comment by Peeterlee** [comment]
no you only need to flex the view that contains everything.
make a variable and make if statements depends on the switches

**Pull request merged**
